version: '3.8'

services:
  # Backend API Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env.production
    volumes:
      # Mount storage directory for file uploads (until migrated to Cloudflare R2)
      - ./backend/storage:/app/storage
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - mindscroll_network

  # Frontend Next.js Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - mindscroll_network

  # Redis for Bull Queue (Optional - can use external Redis service)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - mindscroll_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - mindscroll_network

volumes:
  redis_data:

networks:
  mindscroll_network:
    driver: bridge