#!/bin/bash
# ==============================================================================
# Docker Container Initialization Script
# Creates .env file from environment variables to eliminate Prisma warnings
# ==============================================================================

set -e

echo "🐳 Initializing Docker container..."

# Create .env file from environment variables to satisfy Prisma
cat > /app/.env << EOF
# Generated by docker-init.sh from environment variables
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}
NODE_ENV=${NODE_ENV}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:-}
JWT_SECRET=${JWT_SECRET:-}
JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
CORS_ORIGIN=${CORS_ORIGIN:-}
CLOUDFLARE_R2_ENDPOINT=${CLOUDFLARE_R2_ENDPOINT:-}
CLOUDFLARE_R2_ACCESS_KEY_ID=${CLOUDFLARE_R2_ACCESS_KEY_ID:-}
CLOUDFLARE_R2_SECRET_ACCESS_KEY=${CLOUDFLARE_R2_SECRET_ACCESS_KEY:-}
CLOUDFLARE_R2_BUCKET_NAME=${CLOUDFLARE_R2_BUCKET_NAME:-}
STORAGE_TYPE=${STORAGE_TYPE:-}
EOF

echo "📝 Created .env file for Prisma"

# Execute the original command
exec "$@"